language: r
cache:
- packages
r_packages:
- drat
- styler
- devtools

before_cache:
- Rscript -e 'remotes::install_cran("pkgdown")'
before_install:
- bash travis/make.sh
after_success:
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/drat.sh
- test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "master" && bash
  travis/styler.sh

# deploy:
#   provider: script
#   script: Rscript -e 'pkgdown::deploy_site_github()'
#   skip_cleanup: true
