---
title: "Maps with inset"
author: "Author"
date: "`r Sys.Date()`"
output:
  rmarkdown::html_vignette:
    fig_width: 6
    fig_height: 6
vignette: >
  %\VignetteIndexEntry{Maps with inset}
  %\VignetteEncoding{UTF-8}
  %\VignetteEngine{knitr::rmarkdown}
editor_options: 
  chunk_output_type: console
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggplot2)
library(fhiplot)

pd <- fhidata::norway_map_counties
data <- unique(pd[,c("location_code")])
suppressWarnings(data[,category:=rep(c("Good","Normal","Neutral","Bad","Very Bad"),each=4)[1:.N]])
data[,category_with_missing:=category]
data[1,category_with_missing:="Missing"]
data[,category:=factor(category,levels=c("Good","Normal","Neutral","Bad","Very Bad"))]
data[,category_with_missing:=factor(category_with_missing,levels=c("Good","Normal","Neutral","Bad","Very Bad","Missing"))]
pd[data,on="location_code",category:=category]
pd[data,on="location_code",category_with_missing:=category_with_missing]
pd[location_code == "county02", category:='Very Bad']

```

## Maps with inset for Oslo and Akershus


We create a normal map and add Oslo and Akershus as an inset.

```{r}


q <- ggplot()
q <- q + geom_polygon(data = pd, aes( x = long, y = lat, group = group, fill=category), color="black", size=0.25)
q <- q + coord_quickmap()
q <- q + fhiplot::scale_fill_fhi("Category",palette = "map_seq_complete", direction = 1)
q <- q + labs(title="Norway map")
q <- q + theme_void()

# This adds the inset

q_oslo <-  ggplot() + 
    geom_polygon(data = pd[location_code %in% c("county02", "county03")]
                ,aes( x = long, y = lat, group = group, fill=category), color="black", size=0.25) +
    coord_quickmap() +
    fhiplot::scale_fill_fhi("Category",palette = "map_seq_complete", direction = 1) +
    labs(title="Oslo and Akershus") +
    theme_void() + 
    theme(plot.title = element_text(size = 8,))
map <- q + 
    annotation_custom(
        ggplotGrob(q_oslo), 
        xmin = 10, xmax = 35, ymin = 60, ymax = 65
    )
map
```
